server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos 服务器地址
        # service: userservice       # 可选：若不配置，默认使用 spring.application.name 的值
        cluster-name: HZ # 集群名称
        username: nacos
        password: nacos
        namespace: e05e812f-cf2c-4376-b0e6-c2e07f63171b
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: e05e812f-cf2c-4376-b0e6-c2e07f63171b
        file-extension: yaml
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        - id: user-service # 路由标示，必须唯一
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking awesome! # 1
#            - AddXXXRequestHeader=Truth,Itcast is freaking awesome! # 2
#            - AddXXXRequestHeader=Truth,Itcast is freaking awesome! # 3
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!  #1
#        - AddXXXRequestHeader=Truth,Itcast is freaking awesome!  #2
#        - AddXXXRequestHeader=Truth,Itcast is freaking awesome!  #3